set defa to C:\rp_orion.v2\001d\06
use cuentac
zap
use CUENTAD
zap
use recibo
zap
close all
use facturA
zap
close all
use detallE
zap
close all
use fpagov
zap
close all
use almacen
zap
close all
use saldoini
zap
close all
use cpedidov
zap
close all
use ccotizav
zap
close all
use cordenc
zap
use producto
zap
use productb
zap
use precios
zap
use familia
zap
use subfamil
zap
use seccion
zap
use categori
zap
use linea
zap
use color
zap
use proveedo
zap
use clientes
zap
close all


